### ISSUE TITLE
Include xmlns attribute to make the svg includabel

### ISSUE THREAD

**Issue by k-nut** [juliuste/parliament-svg#5]
I tried to reference the created svg source (pulled out into a file) recently in an `img` element but it would not render correctly. This is because the created svg does not contain the `xmlns="http://www.w3.org/2000/svg"` tag in the root element which is required for anything other than inline svgs (see [this stackoverflow answer](https://stackoverflow.com/a/34249810/4099396)).

As the attribute is ignored in inlined svgs I think that it would be safe to include this. If you agree I'll happily provide a PR for this.

**Comment by juliuste** [comment]
Done (: (Would have waited for your PR but I thought I could do it as well to speed things up a little since it already took me 7 days to respond 😆 )
