### ISSUE TITLE
allow virtual-dom implementation as a parameter

### ISSUE THREAD

**Issue by derhuerst** [juliuste/parliament-svg#9]
I just did some research on virtual DOM implementations and it would like to use [Snabbdom](https://github.com/snabbdom/snabbdom#snabbdom) instead of [virtual-dom](https://github.com/Matt-Esch/virtual-dom#virtual-dom), which [doesn't seem to be maintained anymore](https://github.com/Matt-Esch/virtual-dom/issues/436).

Therefore I'd like to use `snabbdom/h` instead of `virtual-dom/h` to get Snabbdom virtual DOM trees. What do you think about making the `h()` implementation another (optional) parameter?

**Comment by derhuerst** [comment]
So are you ok with this change, given that you tagged this as `enhancement`?

**Comment by juliuste** [comment]
Feel free to PR

**Comment by anSpiros** [comment]
Can it be used with Vue js for example and add a hover effect to each seat?
